-
  name: running docker image on EC2s
  hosts: all
  become: yes
  become_method: sudo
  tasks:
#    - name: Install pip
#      apt: name=python-pip state=present

#    - name: install docker-py
#      pip: name=docker-py


    - name: configure / Update yum packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

