-
  name: ansible audit script
  hosts: all
  become: yes
  become_method: sudo
  tasks:

    - name: see the stuffs inside directory
      shell: ls
      
    - name: command to check with OS this EC2 is using
      shell: cat /etc/*-release

    
    - name: command to check the free space that exists on the machine
      shell: df -h

    - command: cat /etc/*-release
      register: command_output

    - command: echo "this is a amazon linux"
      when: command_output.stdout.find('Amazon Linux AMI') != -1